export const RK_BASE = "/demo/raumkontrast";

export const RK_DEMO = {
  brand: {
    short: "Raumkontrast",
    full: "Raumkontrast Baumann",
    legalName: "Raumkontrast Baumann",
    owner: "Alexander Baumann",
    tagline: "Wohn(t)räume werden Wirklichkeit.",
    navSubtitle: "Raumausstattung · Irschenberg",
    profession: "Raumausstattermeister · Sonnenschutz & Markisen",
  },

  contact: {
    phoneTel: "+491735361077",
    phoneDisplay: "0173 5361077",
    email: "info@raumkontrast-baumann.de",
    addressLine1: "Grub 2b",
    addressLine2: "83737 Irschenberg",
    hours: "Termine nach Vereinbarung",
    facebook: "https://www.facebook.com/raumkontrastbaumann",
    instagram: "https://www.instagram.com/raumkontrast_baumann/",
    whatsappText:
      "Hallo%2C%20ich%20m%C3%B6chte%20einen%20Termin%20f%C3%BCr%20Aufma%C3%9F%20und%20Beratung%20vereinbaren.",
  },

  business: {
    since: 2012,
    trailerSqm: 15,
    regionLabel: "Irschenberg & Oberbayern",
  },
} as const;

export const RK_IMG = {
  hero: `${RK_BASE}/hero-markise.jpg`,
  kassette: `${RK_BASE}/markise-kassette.jpg`,
  zip: `${RK_BASE}/markise-zip.jpg`,
  pergola: `${RK_BASE}/pergola.jpg`,
  plissee: `${RK_BASE}/plissee.jpg`,
  beratung: `${RK_BASE}/beratung.jpg`,
  abend: `${RK_BASE}/terrasse-abend.jpg`,
  gelenkarm: `${RK_BASE}/gelenkarm.jpg`,
  wintergarten: `${RK_BASE}/wintergarten.jpg`,
  doppelrollo: `${RK_BASE}/doppelrollo.jpg`,
  jalousie: `${RK_BASE}/jalousie.jpg`,
  flaechenvorhang: `${RK_BASE}/flaechenvorhang.jpg`,
  insektenschutz: `${RK_BASE}/insektenschutz.jpg`,
  stoff: `${RK_BASE}/stoff.jpg`,
  montage: `${RK_BASE}/montage.jpg`,
  ausstellung: `${RK_BASE}/ausstellung-innen.jpg`,
  ausstellungAnhaenger: `${RK_BASE}/ausstellung-anhaenger.jpg`,
  ausstellungInnen: `${RK_BASE}/ausstellung-innen.jpg`,
  ausstellungStoffe: `${RK_BASE}/ausstellung-stoffe.jpg`,
  ausstellungTeppiche: `${RK_BASE}/ausstellung-teppiche.jpg`,
  ausstellungRechteck: `${RK_BASE}/ausstellung-rechteck.png`,
  gardine: `${RK_BASE}/orig-gardine.png`,
  polster: `${RK_BASE}/orig-polsterei.png`,
  boden: `${RK_BASE}/orig-boden.png`,
  sonnenschutzOrig: `${RK_BASE}/orig-sonnenschutz.png`,
  insektOrig: `${RK_BASE}/orig-insektenschutz.png`,
  trendCord1: `${RK_BASE}/trend-cord-1.jpg`,
  trendCord2: `${RK_BASE}/trend-cord-2.jpg`,
  trendCord3: `${RK_BASE}/trend-cord-3.jpg`,
  trendEnergie: `${RK_BASE}/trend-energie.png`,
  trendFresh: `${RK_BASE}/trend-fresh.jpg`,
  trendDouble: `${RK_BASE}/trend-double.jpg`,
  trendSumba: `${RK_BASE}/trend-sumba.jpg`,
  trendVogue: `${RK_BASE}/trend-vogue.jpg`,
  trendOat: `${RK_BASE}/trend-oat.jpg`,
  trendMineral: `${RK_BASE}/trend-mineral.jpg`,
  gardineHanni: `${RK_BASE}/gardine-hanni.jpg`,
  gardineInspire: `${RK_BASE}/gardine-inspire.jpg`,
  gardineTimber: `${RK_BASE}/gardine-timber.jpg`,
  gardineCountry: `${RK_BASE}/gardine-country.jpg`,
  gardineSoraya: `${RK_BASE}/gardine-soraya.jpg`,
  gardineMika: `${RK_BASE}/gardine-mika.jpg`,
  polsterBuddy: `${RK_BASE}/polster-buddy.jpg`,
  polsterLovely: `${RK_BASE}/polster-lovely.jpg`,
  polsterTreviso: `${RK_BASE}/polster-treviso.jpg`,
  polsterScandi: `${RK_BASE}/polster-scandi.jpg`,
  polsterSamurai: `${RK_BASE}/polster-samurai.jpg`,
  bodenParkett: `${RK_BASE}/boden-parkett-1.jpg`,
  bodenEicheVintage: `${RK_BASE}/boden-eiche-vintage.jpg`,
  bodenEicheWega: `${RK_BASE}/boden-eiche-wega.jpg`,
  bodenDiamant: `${RK_BASE}/boden-diamanteiche.jpg`,
  bodenLaminat: `${RK_BASE}/boden-laminat.jpg`,
  bodenKork: `${RK_BASE}/boden-kork.jpg`,
  bodenDesign: `${RK_BASE}/boden-design.jpg`,
  bodenTeppich1: `${RK_BASE}/boden-teppich-1.jpg`,
  bodenTeppich2: `${RK_BASE}/boden-teppich-2.jpg`,
  sonneMadera: `${RK_BASE}/sonne-madera.jpg`,
  sonnePinta: `${RK_BASE}/sonne-pinta.jpg`,
  sonneSpring: `${RK_BASE}/sonne-spring.jpg`,
  sonneDuette: `${RK_BASE}/sonne-duette.jpg`,
  sonneElegance: `${RK_BASE}/sonne-elegance.jpg`,
  sonneTwinline: `${RK_BASE}/sonne-twinline.jpg`,
  sonneMarkise: `${RK_BASE}/sonne-markise.jpg`,
  sonneUeberdachung: `${RK_BASE}/sonne-ueberdachung.jpg`,
} as const;

export const RK_PARTNERS = [
  {
    name: "Saum & Viebahn",
    href: "https://www.saum-und-viebahn.de/",
    logo: `${RK_BASE}/partner-saum-viebahn.png`,
    focus: "Gardinen- und Dekostoffe",
  },
  {
    name: "JAB Anstoetz",
    href: "https://www.jab.de/",
    logo: `${RK_BASE}/partner-jab.png`,
    focus: "Textilien & Raumkonzepte",
  },
  {
    name: "Trend Stoff",
    href: "http://www.trend-stoff.de/",
    logo: `${RK_BASE}/partner-trendstoff.png`,
    focus: "Aktuelle Stoffkollektionen",
  },
  {
    name: "Interstil",
    href: "https://interstil.de/startseite.html",
    logo: `${RK_BASE}/partner-interstil.png`,
    focus: "Sonnenschutzsysteme",
  },
  {
    name: "Leha",
    href: "https://www.leha.de/",
    logo: `${RK_BASE}/partner-leha.png`,
    focus: "Markisen & Sonnenschutz",
  },
  {
    name: "Neher",
    href: "https://www.neher.de/",
    logo: `${RK_BASE}/partner-neher.png`,
    focus: "Insekten- und Pollenschutz",
  },
  {
    name: "JOKA",
    href: "https://www.joka.de/",
    logo: `${RK_BASE}/partner-joka.png`,
    focus: "Bodenbeläge",
  },
  {
    name: "Fine",
    href: "https://www.fine.at/",
    logo: `${RK_BASE}/partner-fine.png`,
    focus: "Parkett & Designböden",
  },
  {
    name: "Pallmann",
    href: "http://www.pallmann.net/",
    logo: `${RK_BASE}/partner-pallmann.png`,
    focus: "Bodenpflege & Verlegung",
  },
  {
    name: "Mapei",
    href: "https://www.mapei.com/de/de-de/startseite",
    logo: `${RK_BASE}/partner-mapei.png`,
    focus: "Verlegesysteme",
  },
] as const;
