const A = "/demo/stelzer-hesselmann";

export const AA = {
  assets: "/demo/stelzer-hesselmann",
  brand: {
    short: "Stelzer & Heßelmann",
    stacked: ["Stelzer", "&", "Heßelmann"] as const,
    full: "Stelzer & Heßelmann Bedachungen GmbH",
    tagline: "Nah. Lokal. Präsent.",
    profession: "Bedachungen",
  },
  place: {
    village: "Oberhausen",
    region: "Holten",
    address1: "Graßhofstraße 204",
    address2: "46147 Oberhausen",
    address3: "Holten",
  },
  contact: {
    phoneTel: "+49208680806",
    phoneDisplay: "0208 680806",
    mobileTel: "+4917616808060",
    mobileDisplay: "0176 16808060",
    whatsapp: "https://wa.me/4917616808060",
    email: "info@stelzerhesselmann.de",
    hours: "Büro Mo–Fr 8–14 Uhr",
    siteHours: "Baustelle Mo–Do 7–16 Uhr, Fr 7–13 Uhr",
  },
  makers: {
    wood: { name: "Marcel Stelzer", role: "Geschäftsführer" },
    clay: { name: "Georg Heßelmann", role: "Geschäftsführer" },
  },
  legal: {
    court: "Amtsgericht Duisburg, HRB 35023",
    chamber: "HWK Düsseldorf",
    vat: "USt-IdNr. 349 682 829",
  },
  youforge: {
    label: "Living Demo",
    studio: "YouForge",
    href: "/",
  },
} as const;

export const AA_IMG = {
  hero: `${A}/tag-dach.jpg`,
  heroFilm: `${A}/hero.mp4`,
  flach: `${A}/tag-flach.jpg`,
  ziegel: `${A}/tag-ziegel.jpg`,
  schiefer: `${A}/tag-schiefer.jpg`,
  blech: `${A}/tag-blech.jpg`,
  fenster: `${A}/fenster.jpg`,
  pv: `${A}/pv.jpg`,
  first: `${A}/first.jpg`,
  ort: `${A}/ort.jpg`,
  hand: `${A}/hand.jpg`,
  tagFenst: `${A}/tag-fenster.jpg`,
  tagPv: `${A}/tag-pv.jpg`,
  tagOrt: `${A}/tag-ort.jpg`,
  altFlach: `${A}/flach.jpg`,
  altZiegel: `${A}/ziegel.jpg`,
  altSchiefer: `${A}/schiefer.jpg`,
  altBlech: `${A}/blech.jpg`,
  altFenster: `${A}/fenster.jpg`,
  altPv: `${A}/pv.jpg`,
  frameFirst: `${A}/frame-first.jpg`,
  frameHand: `${A}/frame-hand.jpg`,
  frameRinne: `${A}/frame-rinne.jpg`,
  frameOrt: `${A}/frame-ort.jpg`,
  newsMesse: `${A}/news-messe.jpg`,
  newsStand: `${A}/news-stand.jpg`,
  newsMaibaum: `${A}/news-maibaum.jpg`,
  newsBaelle: `${A}/news-baelle.jpg`,
  logo: `${A}/logo.png`,
  logoInk: `${A}/logo-ink.png`,
} as const;
